# Generated by Django 5.1 on 2024-10-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_avatar_id',
            field=models.IntegerField(default=0, verbose_name='Id of current Title user is displaying'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_title_id',
            field=models.IntegerField(default=0, verbose_name='Id of current Title user is displaying'),
        ),
    ]
