# Generated by Django 5.1 on 2024-10-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_avatar_users_remove_title_users'),
        ('user', '0002_remove_customuser_title_customuser_current_avatar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatars',
            field=models.ManyToManyField(to='marketplace.avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='titles',
            field=models.ManyToManyField(to='marketplace.title'),
        ),
    ]
