# Generated by Django 5.1 on 2024-10-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_avatar_users_remove_title_users'),
        ('user', '0004_rename_avatars_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatars',
            field=models.ManyToManyField(related_name='users', to='marketplace.avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='titles',
            field=models.ManyToManyField(related_name='users', to='marketplace.title'),
        ),
    ]
