# Generated by Django 5.1 on 2024-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_avatar_users_remove_title_users'),
        ('user', '0005_remove_customuser_avatar_remove_customuser_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatars',
            field=models.ManyToManyField(blank=True, default=list, related_name='users', to='marketplace.avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='titles',
            field=models.ManyToManyField(blank=True, default=list, related_name='users', to='marketplace.title'),
        ),
    ]
