# Generated by Django 5.1 on 2024-10-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_avatar_date_time_unlisted_and_more'),
        ('user', '0006_alter_customuser_avatars_alter_customuser_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_avatar_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_title_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.title'),
        ),
    ]
