services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - django-postgres

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - react-django
      - django-postgres
  
  frontend:
    build: ./frontend
    
    volumes:
      - ./frontend/:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
  
    depends_on:
      - backend

    networks:
      - react-django

networks:
  react-django:
  django-postgres:

volumes:
  postgres_data:
  media:
  static:
