services:
  # api_db:
  #  image: postgres:13
  #  volumes:
  #    - api_postgres_data:/var/lib/postgresql/data/
  #  env_file:
  #    - ./.env.prod.db
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn gamification_tool.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    #depends_on:
    #  - api_db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

volumes:
  # api_postgres_data:
  static_volume:
  media_volume:

# Postgres commented out
# but could be used instead of the AWS RDS instance if preferred