# Generated by Django 5.1 on 2024-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points_accumulated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='points_spendable',
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_points',
            field=models.IntegerField(default=0, verbose_name='Total experience points user has accumulated'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_points',
            field=models.IntegerField(default=0, verbose_name='Copy of experience points. Consumable at shops.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
