# Generated by Django 5.1 on 2024-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_points_accumulated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience_points',
            field=models.IntegerField(default=0, verbose_name='Experience points'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_points',
            field=models.IntegerField(default=0, verbose_name='Shop points'),
        ),
    ]
