# Generated by Django 5.1 on 2024-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemorygamescore',
            name='eligible_for_leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
