# Generated by Django 5.1 on 2024-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of marketplace item')),
                ('cost', models.IntegerField(default=0, verbose_name='Price in shop_points')),
                ('partner', models.CharField(max_length=50, verbose_name='Name of collaborator')),
                ('description', models.CharField(max_length=255, verbose_name='Description of the item')),
                ('date_time_added', models.DateTimeField(verbose_name='When ttem was added to the marketplace')),
                ('is_listed', models.BooleanField(verbose_name='Is item still purchaseable')),
                ('date_time_unlisted', models.DateTimeField(verbose_name='When item became no longer purchaseable')),
                ('img_url', models.ImageField(upload_to=None, verbose_name='URL of image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of marketplace item')),
                ('cost', models.IntegerField(default=0, verbose_name='Price in shop_points')),
                ('partner', models.CharField(max_length=50, verbose_name='Name of collaborator')),
                ('description', models.CharField(max_length=255, verbose_name='Description of the item')),
                ('date_time_added', models.DateTimeField(verbose_name='When ttem was added to the marketplace')),
                ('is_listed', models.BooleanField(verbose_name='Is item still purchaseable')),
                ('date_time_unlisted', models.DateTimeField(verbose_name='When item became no longer purchaseable')),
                ('text', models.CharField(max_length=50, verbose_name='Title text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
