# Generated by Django 5.1 on 2024-09-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='date_time_unlisted',
            field=models.DateTimeField(verbose_name='Last time when item became unlisted/purchaseable'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='is_listed',
            field=models.BooleanField(default=False, verbose_name='Is item purchaseable?'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_time_unlisted',
            field=models.DateTimeField(verbose_name='Last time when item became unlisted/purchaseable'),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_listed',
            field=models.BooleanField(default=False, verbose_name='Is item purchaseable?'),
        ),
    ]
