# Generated by Django 5.1 on 2024-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_avatar_date_time_unlisted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='date_time_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When ttem was added to the marketplace'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_time_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When ttem was added to the marketplace'),
        ),
    ]
