# Generated by Django 5.1 on 2024-09-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_avatar_date_time_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='date_time_unlisted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last time when item became unlisted/purchaseable'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of the item'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='partner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of collaborator'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_time_unlisted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last time when item became unlisted/purchaseable'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of the item'),
        ),
        migrations.AlterField(
            model_name='title',
            name='partner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of collaborator'),
        ),
    ]
