# Generated by Django 5.1 on 2024-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_avatar_date_time_unlisted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='img_url',
            field=models.ImageField(upload_to='avatars', verbose_name='URL of image'),
        ),
    ]
