# Generated by Django 5.1 on 2024-10-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_avatar_users_title_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='users',
        ),
        migrations.RemoveField(
            model_name='title',
            name='users',
        ),
    ]
