# Generated by Django 5.1 on 2024-10-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_avatar_users_remove_title_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='URL of image'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of marketplace item'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of marketplace item'),
        ),
        migrations.AlterField(
            model_name='title',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title text'),
        ),
    ]
