# Generated by Django 5.1 on 2024-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_avatar_img_url_alter_avatar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='Name of marketplace item'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='Name of marketplace item'),
        ),
    ]
