# Generated by Django 5.1 on 2024-10-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_avatar_name_alter_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='date_time_listed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime when item was listed'),
        ),
        migrations.AddField(
            model_name='title',
            name='date_time_listed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime when item was listed'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='date_time_unlisted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last datetime when item became unlisted/unpurchaseable'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_time_unlisted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last datetime when item became unlisted/unpurchaseable'),
        ),
    ]
