# Generated by Django 5.1 on 2024-10-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_avatar_date_time_listed_title_date_time_listed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='date_time_unlisted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime when item became unlisted'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_time_unlisted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime when item became unlisted'),
        ),
    ]
