# Generated by Django 5.1 on 2024-08-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='Location name')),
                ('date_visited', models.DateTimeField(verbose_name='Date visited')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event name')),
                ('date_visited', models.DateTimeField(verbose_name='Date visited')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in.location')),
            ],
        ),
    ]
