# Generated by Django 5.1 on 2024-08-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visit_counter',
            field=models.IntegerField(default=0, verbose_name='Number of event attendances'),
        ),
    ]
